export default {
	SUCCESS: "_SUCCESS",
  ERROR: "_ERROR",
  
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTER: 'USER_REGISTER',

  TRENDING_CAMPAIGNS: 'TRENDING_CAMPAIGNS',

  BASIC_ACTION: "BASIC_ACTION",
  BASIC_ACTION_SUCCESS: "BASIC_ACTION_SUCCESS",
  BASIC_ACTION_ERROR: "BASIC_ACTION_ERROR"
};