export default {
	SUCCESS: "_SUCCESS",
  ERROR: "_ERROR",
  
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_USERNAME_UPDATE: 'USER_USERNAME_UPDATE',

  TRENDING_CAMPAIGNS: 'TRENDING_CAMPAIGNS',
  FEATURED_CAMPAIGNS: 'FEATURED_CAMPAIGNS',

  BASIC_ACTION: "BASIC_ACTION",
  BASIC_ACTION_SUCCESS: "BASIC_ACTION_SUCCESS",
  BASIC_ACTION_ERROR: "BASIC_ACTION_ERROR"
};